# SPDX-FileCopyrightText: 2025 SecPal Contributors
# SPDX-License-Identifier: CC0-1.0
#
# Redocly Configuration for SecPal API
#
# Rules customization:
# - operation-4xx-response: Disabled because health check endpoints
#   semantically only return 200 (healthy) or 503 (unhealthy).
#   Client errors (4xx) are not applicable to monitoring endpoints
#   that accept no parameters and perform no user-driven operations.
#
#   Future endpoints that accept parameters MUST include appropriate
#   4xx responses (400, 401, 403, 404, etc.) in their OpenAPI specs.

extends:
  - recommended

rules:
  operation-4xx-response: off
