# SPDX-FileCopyrightText: 2025 SecPal
# SPDX-License-Identifier: AGPL-3.0-or-later

# Issue templates for SecPal contracts repository
# Templates are based on org-wide templates from .github repository
# Note: GitHub does not auto-import ISSUE_TEMPLATE/ from org repos (limitation)

blank_issues_enabled: false

contact_links:
  - name: 💬 Discussions
    url: https://github.com/orgs/SecPal/discussions
    about: Ask questions or discuss ideas with the community
