# SPDX-FileCopyrightText: 2025 SecPal
# SPDX-License-Identifier: CC0-1.0

name: CLA Assistant

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  cla-check:
    runs-on: ubuntu-latest
    steps:
      - name: CLA Assistant
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_PAT }}
        with:
          path-to-signatures: .github/signatures/cla.json
          path-to-document: https://github.com/SecPal/.github/blob/main/CLA.md
          branch: main
          allowlist: bot*,dependabot*
          remote-organization-name: SecPal
          remote-repository-name: .github
          create-file-commit-message: 'chore: create CLA signatures file'
          signed-commit-message: 'chore: $contributorName has signed the CLA'
          custom-notsigned-prcomment: 'Thank you for your contribution! Before we can merge this PR, you need to sign our [Contributor License Agreement (CLA)](https://github.com/SecPal/.github/blob/main/CLA.md).<br/><br/>Please comment with:<br/>**I have read the CLA Document and I hereby sign the CLA**'
          custom-pr-sign-comment: 'I have read the CLA Document and I hereby sign the CLA'
          custom-allsigned-prcomment: 'All contributors have signed the CLA. ✅'
          lock-pullrequest-aftermerge: false
