# SPDX-FileCopyrightText: 2025 SecPal
# SPDX-License-Identifier: CC0-1.0

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  pr-size:
    uses: SecPal/.github/.github/workflows/reusable-pr-size.yml@main
    with:
      max-lines: 600
      exclude-patterns: ''
