# SPDX-FileCopyrightText: 2025-2026 SecPal
# SPDX-License-Identifier: CC0-1.0

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  pr-size:
    # yamllint disable-line rule:line-length
    uses: SecPal/.github/.github/workflows/reusable-pr-size.yml@f8cabffc336002e72bb7a25ef40331fc58b0e83d # main
    with:
      max-lines: 600
      exclude-patterns: ''
