# SPDX-FileCopyrightText: 2025-2026 SecPal
# SPDX-License-Identifier: CC0-1.0

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  pr-size:
    # yamllint disable-line rule:line-length
    uses: SecPal/.github/.github/workflows/reusable-pr-size.yml@4a000f9a56afac7d0f8594d397512c5a371ef097 # main
    with:
      max-lines: 600
      exclude-patterns: ''
